# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Mikel/Dropbox/School/EE 214/Project 6/Project 6.3/VGA_Display_controller/VGA_Display_controller.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Mikel/Dropbox/School/EE 214/Project 6/Project 6.3/VGA_Display_controller/VGA_Display_controller.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Mikel/Dropbox/School/EE 214/Project 6/Project 6.3/VGA_Display_controller/VGA_Display_controller.srcs/sources_1/imports/new/dff.v}
  {C:/Users/Mikel/Dropbox/School/EE 214/Project 6/Project 6.3/VGA_Display_controller/VGA_Display_controller.srcs/sources_1/new/Vert_Count.v}
  {C:/Users/Mikel/Dropbox/School/EE 214/Project 6/Project 6.3/VGA_Display_controller/VGA_Display_controller.srcs/sources_1/new/Vert_cmp.v}
  {C:/Users/Mikel/Dropbox/School/EE 214/Project 6/Project 6.3/VGA_Display_controller/VGA_Display_controller.srcs/sources_1/new/M_stand.v}
  {C:/Users/Mikel/Dropbox/School/EE 214/Project 6/Project 6.3/VGA_Display_controller/VGA_Display_controller.srcs/sources_1/new/Hor_Count.v}
  {C:/Users/Mikel/Dropbox/School/EE 214/Project 6/Project 6.3/VGA_Display_controller/VGA_Display_controller.srcs/sources_1/new/Hor_cmp.v}
  {C:/Users/Mikel/Dropbox/School/EE 214/Project 6/Project 6.3/VGA_Display_controller/VGA_Display_controller.srcs/sources_1/imports/new/cmp.v}
  {C:/Users/Mikel/Dropbox/School/EE 214/Project 6/Project 6.3/VGA_Display_controller/VGA_Display_controller.srcs/sources_1/imports/new/clk_divider.v}
  {C:/Users/Mikel/Dropbox/School/EE 214/Project 6/Project 6.3/VGA_Display_controller/VGA_Display_controller.srcs/sources_1/imports/new/ClkDivider.v}
  {C:/Users/Mikel/Dropbox/School/EE 214/Project 6/Project 6.3/VGA_Display_controller/VGA_Display_controller.srcs/sources_1/new/VGA_Controller.v}
}
read_xdc {{C:/Users/Mikel/Dropbox/School/EE 214/Project 6/Project 6.3/VGA_Display_controller/VGA_Display_controller.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Mikel/Dropbox/School/EE 214/Project 6/Project 6.3/VGA_Display_controller/VGA_Display_controller.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc}}]

catch { write_hwdef -file VGA_Controller.hwdef }
synth_design -top VGA_Controller -part xc7a100tcsg324-1
write_checkpoint VGA_Controller.dcp
catch { report_utilization -file VGA_Controller_utilization_synth.rpt -pb VGA_Controller_utilization_synth.pb }
